import json,os,subprocess,sys,tempfile,unittest
from pathlib import Path
from unittest.mock import patch
ROOT=Path(__file__).resolve().parents[1];sys.path[:0]=[str(ROOT),str(ROOT/'collectors/system')]
from completeness import Coverage,publish
import drive_health as drives
import firewall_inventory as firewall
import network_inventory as network
import storage_inventory as storage
import runtime_history as history
import startup_launcher as launcher
import access_scripts

class DriveHealthTests(unittest.TestCase):
    def test_nvme_health_and_unknown_are_distinct(self):
        raw={'serial_number':'fixture','smart_status':{'passed':False},'nvme_smart_health_information_log':{'critical_warning':8,'temperature':45,'percentage_used':102,'available_spare':5,'available_spare_threshold':10,'media_errors':3}}
        row=drives.metrics(raw,'/dev/test');self.assertEqual(row['failed_count'],1);self.assertEqual(row['wear_used_percent'],102);self.assertEqual(row['spare_below_threshold_count'],1);self.assertEqual(row['media_errors_count'],3);self.assertIsNone(row['pending_sectors_count'])
    def test_vendor_attribute_interpretation_is_narrow(self):
        raw={'ata_smart_attributes':{'table':[{'id':5,'name':'Vendor_Unknown','raw':{'value':999}},{'id':197,'name':'Current_Pending_Sector','raw':{'value':4}}]}}
        row=drives.metrics(raw,'drive');self.assertIsNone(row['reallocated_sectors_count']);self.assertEqual(row['pending_sectors_count'],4)
    def test_health_error_bit_does_not_discard_readings(self):
        payload={'smartctl':{'exit_status':8},'smart_status':{'passed':False}}
        with patch.object(drives.shutil,'which',return_value='/smartctl'),patch.object(drives.subprocess,'run',return_value=subprocess.CompletedProcess([],8,json.dumps(payload).encode(),b'')):
            self.assertEqual(drives.invoke(['-a','/dev/test'])[1],8)
        payload['smartctl']['exit_status']=2
        with patch.object(drives.shutil,'which',return_value='/smartctl'),patch.object(drives.subprocess,'run',return_value=subprocess.CompletedProcess([],2,json.dumps(payload).encode(),b'')):
            with self.assertRaises(RuntimeError):drives.invoke(['-a','/dev/test'])
    def test_one_device_failure_and_runtime_exclusion(self):
        with tempfile.TemporaryDirectory() as td:
            def fake(args):
                if args[-1]=='/dev/bad':raise RuntimeError('unavailable')
                return {'model_name':'fixture','serial_number':'abc','temperature':{'current':30},'smart_status':{'passed':True}},0
            with patch.object(drives,'invoke',side_effect=fake):scopes,failures=drives.collect(td,devices=['/dev/good','/dev/bad'])
            self.assertEqual([s['status'] for s in scopes],['complete','failed']);self.assertEqual(len(failures),1)
            publish(td,scopes);c=Coverage(td);self.assertFalse(any(f.startswith('telemetry') for f in c.files));self.assertEqual(len(c.files),1)
    def test_configuration_disabled_keeps_runtime_separate(self):
        with tempfile.TemporaryDirectory() as td,patch.dict(os.environ,{'CONFIGBACKUP_SECTIONS':'{"configuration":false}'}),patch.object(drives,'invoke',return_value=({'model_name':'x','smart_status':{'passed':True}},0)):
            scopes,_=drives.collect(td,devices=['/dev/x']);self.assertEqual(scopes[0]['status'],'disabled');self.assertTrue((Path(td)/'telemetry/drives/health.json').exists())
    def test_apple_missing_member_and_states(self):
        row={'AppleRAIDSetUUID':'set','Status':'Offline','Members':[{'AppleRAIDMemberUUID':'a','BSD Name':'disk4','MemberStatus':'Online'},{'AppleRAIDMemberUUID':'b'}]}
        h=storage.apple_raid_health({'AppleRAIDSets':[row]})[0];self.assertEqual(h['missing_members_count'],1);self.assertEqual(h['offline_count'],1);self.assertIsNone(h['degraded_count'])
        row['Status']='Degraded';h=storage.apple_raid_health({'AppleRAIDSets':[row]})[0];self.assertEqual(h['degraded_count'],1);self.assertEqual(h['offline_count'],0)
        row['Status']='Unrecognized';self.assertIsNone(storage.apple_raid_health({'AppleRAIDSets':[row]})[0]['degraded_count'])

class FirewallTests(unittest.TestCase):
    def test_nft_counter_normalization_preserves_quota_and_rule_order(self):
        raw={'nftables':[{'metainfo':{'version':'x'}},{'rule':{'handle':7,'expr':[{'counter':{'packets':50,'bytes':700}},{'quota':{'val':123,'used':20}},{'match':{'left':{'payload':{'bytes':10}},'right':42}}]}}]}
        value=firewall.nft_configuration(raw);expr=value['nftables'][0]['rule']['expr'];self.assertEqual(expr[0],{'counter':{}});self.assertEqual(expr[1],{'quota':{'val':123}});self.assertEqual(expr[2]['match']['left']['payload']['bytes'],10)
    def test_iptables_header_and_policy_counts_only(self):
        raw='# Generated by iptables-save v1.8.9 on now\n*filter\n:INPUT ACCEPT [10:900]\n-A INPUT -m comment --comment "bytes=100" -j ACCEPT\nCOMMIT\n# Completed on now\n'
        value=firewall.iptables_configuration(raw);self.assertNotIn('now',value);self.assertIn('[0:0]',value);self.assertIn('bytes=100',value)
    def test_failed_firewall_does_not_certify_empty(self):
        with tempfile.TemporaryDirectory() as td,patch.object(firewall,'text',side_effect=PermissionError('denied')):
            scopes,failures=firewall.collect(td,'darwin');self.assertTrue(failures);self.assertEqual(next(s for s in scopes if s['path']=='firewall/pf-rules')['status'],'failed');publish(td,scopes);c=Coverage(td);self.assertFalse(c.permits_deletion('firewall/pf-rules/configuration.json'))
    def test_network_runtime_not_certified_and_disabled_probes_skipped(self):
        with tempfile.TemporaryDirectory() as td,patch.dict(os.environ,{'CONFIGBACKUP_SECTIONS':'{"shares":false}'}),patch.object(network,'text',return_value='fixture') as call:
            scopes,failures=network.collect(td,platform_name='darwin',runtime=True);self.assertTrue(all(s['status']=='disabled' for s in scopes));self.assertEqual(call.call_count,5);publish(td,scopes);self.assertFalse(Coverage(td).files);self.assertTrue((Path(td)/'telemetry/network/inventory.json').exists())
    def test_filesystems_independent_when_one_device_unreadable(self):
        with tempfile.TemporaryDirectory() as td:
            def fake(args):
                if args[0]=='findmnt':return json.dumps({'filesystems':[{'source':'/dev/ok[/subdir]','target':'/ok','fstype':'ext4'},{'source':'/dev/bad','target':'/bad','fstype':'ext4'}]})
                if args[0]=='tune2fs':
                    if args[-1]=='/dev/ok':return 'Filesystem UUID: fixture\nBlock size: 4096\n'
                    raise RuntimeError('device unavailable')
                raise storage.Unavailable('not installed')
            with patch.object(storage,'text',side_effect=fake):scopes,failures=storage.collect(td,'linux')
            ext=[s for s in scopes if s['path'].startswith('storage/ext/filesystems/')];self.assertEqual(sorted(s['status'] for s in ext),['complete','failed']);publish(td,scopes);Coverage(td)

class RuntimeHistoryTests(unittest.TestCase):
    def test_linked_index_never_reads_or_overwrites_external_file(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td);source=base/'source';source.mkdir();(source/'x').write_text('x')
            target=base/'outside';target.write_text('[]');root=base/'history/ports';root.mkdir(parents=True);(root/'index.json').symlink_to(target)
            result=history.capture([self.spec(source)],base/'history',0)[0]
            self.assertEqual(result['status'],'failed');self.assertEqual(target.read_text(),'[]');self.assertFalse((root/'.lock').exists())
    def spec(self,source,**extra):return {'id':'ports','source':str(source),'keep_days':1,'interval_minutes':1,**extra}
    def test_selective_retention_independent_of_config_git(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td);source=base/'source';source.mkdir();(source/'ports.json').write_text('one');(source/'skip.json').write_text('excluded');spec=self.spec(source,include=['ports.json'])
            a=history.capture([spec],base/'history',0)[0];self.assertEqual(a['status'],'captured');first=Path(a['directory']);self.assertFalse((first/'skip.json').exists())
            (source/'ports.json').write_text('two');b=history.capture([spec],base/'history',86401)[0];self.assertEqual(b['retained'],1);self.assertFalse(first.exists());self.assertEqual((Path(b['directory'])/'ports.json').read_text(),'two')
    def test_missing_source_preserves_history_and_does_not_prune(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td);source=base/'source';source.mkdir();(source/'x').write_text('keep');spec=self.spec(source);first=Path(history.capture([spec],base/'history',0)[0]['directory']);(source/'x').unlink();source.rmdir()
            self.assertEqual(history.capture([spec],base/'history',999999)[0]['status'],'failed');self.assertTrue(first.exists())
    def test_failed_source_does_not_prevent_other_source(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td);(base/'good').mkdir();(base/'good/x').write_text('ok');specs=[self.spec(base/'missing'),{**self.spec(base/'good'),'id':'other'}];r=history.capture(specs,base/'history',0);self.assertEqual([x['status'] for x in r],['failed','captured'])
    def test_symlink_and_size_limit_preserve_previous_snapshot(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td);source=base/'source';source.mkdir();(source/'x').write_text('keep');spec=self.spec(source);first=Path(history.capture([spec],base/'history',0)[0]['directory']);(source/'bad').symlink_to(source/'x')
            self.assertEqual(history.capture([spec],base/'history',9999)[0]['status'],'failed');self.assertTrue(first.exists());(source/'bad').unlink()
            self.assertEqual(history.capture([{**spec,'max_file_bytes':1}],base/'history',9999)[0]['status'],'failed');self.assertTrue(first.exists())
    def test_disabled_source_and_interval(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td);source=base/'source';source.mkdir();(source/'x').write_text('x');spec=self.spec(source);history.capture([spec],base/'history',0)
            self.assertEqual(history.capture([spec],base/'history',30)[0]['status'],'interval_not_due');self.assertEqual(history.capture([{**spec,'enabled':False}],base/'history',9999)[0]['status'],'disabled')

class LauncherAndAccessTests(unittest.TestCase):
    def test_shell_launcher_quotes_paths_and_propagates_exit(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td);config=base/"config '$() file.yaml";config.write_text('tasks: []');python=base/"fake python";python.write_text('#!/bin/sh\n[ "$2" = "--config" ] || exit 99\nexit 7\n');python.chmod(0o700)
            files=launcher.generate(config,base/'launcher','linux',str(python));script=next(p for p in files if p.suffix=='.sh');r=subprocess.run(['/bin/sh',str(script)],capture_output=True,text=True);self.assertEqual(r.returncode,7);self.assertEqual(r.stdout,'');self.assertEqual(script.stat().st_mode & 0o777,0o700)
    def test_missing_secret_prevents_python_execution(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td);config=base/'config.yaml';config.write_text('');marker=base/'executed';python=base/'python';python.write_text('#!/bin/sh\ntouch '+str(marker)+'\n');python.chmod(0o700)
            tool=base/'secret-tool';tool.write_text('#!/bin/sh\nexit 1\n');tool.chmod(0o700)
            launcher.generate(config,base/'launcher','linux',str(python),'secret-service',[{'env':'GH_TOKEN','name':"key $(false) ' q"}])
            r=subprocess.run(['/bin/sh',str(base/'launcher/run-configbackup.sh')],env={**os.environ,'PATH':str(base)},capture_output=True,text=True);self.assertEqual(r.returncode,1);self.assertFalse(marker.exists());self.assertEqual(r.stdout,'')
    def test_launcher_does_not_accept_secret_values_or_reserved_environment(self):
        with tempfile.TemporaryDirectory() as td:
            for secret in ({'env':'GH_TOKEN','name':'token','value':'must-not-be-written'},{'env':'PATH','name':'token'}):
                with self.assertRaises(ValueError):launcher.generate('config.yaml',td,'linux','python3','secret-service',[secret])
    def test_powershell_launcher_contains_reference_not_value_and_no_executionpolicy_bypass(self):
        with tempfile.TemporaryDirectory() as td:
            launcher.generate('config.yaml',td,'windows','python','powershell-vault',[{'env':'GH_TOKEN','name':"git's token"}],vault='Vault')
            text=(Path(td)/'run-configbackup.ps1').read_text();self.assertIn("'git''s token'",text);self.assertIn('finally',text);self.assertNotIn('Write-Output $value',text);self.assertNotIn('Bypass',(Path(td)/'run-configbackup.bat').read_text())
    def test_access_scripts_escape_names_and_grant_no_writer_roles(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td);access_scripts.generate('sqlserver',"read]er",["data]base"],base/'sql');script=(base/'sql/grant-read-access.sql').read_text();self.assertIn('[read]]er]',script);self.assertIn('[data]]base]',script);self.assertNotIn('ALTER ROLE [SQLAgentReaderRole]',script);self.assertNotIn('GRANT CONTROL',script)
            access_scripts.generate('postgresql','read"er',['data"base'],base/'pg');script=(base/'pg/grant-cluster-read-access.sql').read_text();self.assertIn('"read""er"',script);self.assertNotIn('GRANT pg_write_all_data',script);self.assertTrue((base/'pg/audit-database-access.sql').exists())
    def test_access_scripts_never_overwrite(self):
        with tempfile.TemporaryDirectory() as td:
            access_scripts.generate('sqlserver','reader',['database'],td)
            with self.assertRaises(ValueError):access_scripts.generate('sqlserver','different',['database'],td)
