"""Read-only firewall policy probes. Rule/anchor order is semantically significant."""
import json
from pathlib import Path
import re
import sys
from completeness import section
from sections import enabled
from storage_inventory import text,Unavailable


def nft_configuration(raw):
    if not isinstance(raw.get('nftables'),list):raise ValueError('Unrecognized nftables JSON')
    # Restrict normalization to actual counter/quota objects. A byte quota or
    # a match against a packet field remains configuration, not a counter.
    def clean(value):
        if isinstance(value,list):return [clean(x) for x in value]
        if not isinstance(value,dict):return value
        out={}
        for key,child in value.items():
            if key=='metainfo':continue
            if key in ('counter','quota') and isinstance(child,dict):
                child={k:v for k,v in child.items() if k not in ({'packets','bytes','handle'} if key=='counter' else {'used','handle'})}
            elif key in ('table','chain','rule','set','flowtable') and isinstance(child,dict):
                child={k:v for k,v in child.items() if k!='handle'}
            out[key]=clean(child)
        return out
    return {'nftables':[clean(x) for x in raw['nftables'] if 'metainfo' not in x]}


def iptables_configuration(raw):
    result=[]
    for line in raw.splitlines():
        if re.match(r'^# (Generated by (ip6tables|iptables)-save v\S+ on |Completed on )',line):continue
        if line.startswith(':'):line=re.sub(r'\[\d+:\d+\]$','[0:0]',line)
        result.append(line)
    return '\n'.join(result)+'\n'


def collect(root,platform_name=None):
    root=Path(root);platform_name=platform_name or sys.platform;scopes=[];failures=[]
    def probe(name,fn):
        scope='firewall/'+name
        if not enabled('configuration') or not enabled(scope):
            scopes.append(section(root,scope,'disabled','Disabled by configuration'));return
        try:
            data=fn();target=root/scope/'configuration.json';target.parent.mkdir(parents=True,exist_ok=True)
            target.write_text(json.dumps(data,sort_keys=True,indent=2)+'\n');scopes.append(section(root,scope))
        except Unavailable as exc:scopes.append(section(root,scope,'not_applicable',str(exc)))
        except Exception as exc:
            scopes.append(section(root,scope,'failed',str(exc)));failures.append({'section':scope,'error':str(exc)})
    def definitions(paths):
        rows=[]
        for base in paths:
            base=Path(base)
            if not base.exists():continue
            for path in sorted(base.rglob('*')) if base.is_dir() else [base]:
                if path.is_file():rows.append({'path':str(path),'content':path.read_text()})
        return rows
    if platform_name.startswith('linux'):
        probe('nftables',lambda:nft_configuration(json.loads(text(['nft','-j','list','ruleset']))))
        for kind,command in [('iptables-ipv4','iptables-save'),('iptables-ipv6','ip6tables-save')]:
            probe(kind,lambda command=command:iptables_configuration(text([command])))
        probe('definitions',lambda:definitions(['/etc/nftables.conf','/etc/nftables.d','/etc/iptables','/etc/ufw','/etc/firewalld']))
        for name,args in [('firewalld-effective',['--list-all-zones']),('firewalld-permanent',['--permanent','--list-all-zones'])]:
            probe(name,lambda args=args:text(['firewall-cmd',*args]))
        probe('ufw-effective',lambda:text(['ufw','status','verbose']))
    elif platform_name=='darwin':
        base='/usr/libexec/ApplicationFirewall/socketfilterfw'
        for name,flag in [('state','--getglobalstate'),('block-all','--getblockall'),('stealth','--getstealthmode'),('signed-apps','--getallowsigned'),('applications','--listapps')]:
            probe('application/'+name,lambda flag=flag:text([base,flag]))
        probe('pf-definitions',lambda:definitions(['/etc/pf.conf','/etc/pf.anchors']))
        # Recursive anchor rules and NAT, no statistics/state table and no loads.
        probe('pf-rules',lambda:text(['pfctl','-a','*','-sr']))
        probe('pf-nat',lambda:text(['pfctl','-a','*','-sn']))
    return scopes,failures
